apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  externalIPs:
    - <ノードの内部IP>
    - <ノードの内部IP>
